version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ordersystem:
    build:
      context: .
      dockerfile: cmd/ordersystem/Dockerfile
    container_name: ordersystem
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - 8080:8080
    environment:
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: orders
      WEB_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 50051
      GRAPHQL_SERVER_PORT: 8080
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
